### ISSUE TITLE
Parts List / BOM

### ISSUE THREAD

**Issue by jappyjan** [c0pperdragon/HotPlate#1]
Hello,

Where can i find a BOM of Parts that i need to buy to build this project?

PS: awesome project! sad that it is already sold out on tindie, otherwise i would have bought a kit over there <3

**Comment by c0pperdragon** [comment]
I have deliberately not provided a BOM to make it not _all_ too easy to copy my design. Also I can not really specify the parts, as the availability (especially for cheap OLEDs) is a bit tricky. You basically have to use what you can get from AliExpres this week.

When demand stays high, I will make more devices. But I need to raise the price a bit to not only cover my expenses but to get a little money for my time.

Anyway, I have improved the PCB design a bit and also updated the schematics. Using the schematics you should be able to order the necessary parts if you do a bit of work to figure out the IC packages sizes.
